export const translations = {
    it: {
        name: "SALVATORE <br> BUTERA",
        description: "SVILUPPATORE FRONT-END",
        introductionTitle: "INTRODUZIONE",
        introduction: "Sono un Jr Full Stack Web Developer appassionato di informatica e grafica. So utilizzare numerosi framework per lo sviluppo di applicazioni web sia lato front-end che back-end. Sono sempre pronto a sfidare me stesso e imparare cose nuove ogni giorno.",
        experience: "ESPERIENZA",
        softwareDeveloper: "Software Developer Engineer",
        ntt: "NTT DATA",
        period1: "<span class=\"clock\"><i class=\"fa fa-clock-o\" aria-hidden=\"true\"></i></span> Feb 2022 - in corso </span>",
        mansion1: "<b> Apprendistato </b>",
        experienceDescription: "<tag-lab>Angular</tag-lab>  <tag-lab>Typescript</tag-lab>",
        fullStackDeveloper: "Junior Full Stack Developer",
        period2: "<span class=\"clock\"><i class=\"fa fa-calendar\" aria-hidden=\"true\"></i></span> Set 2021 - Mar 2022 </span> ",
        mansion2: "<b>Stage</b>",
        experience2Description: "<p>Durante lo stage presso NTT DATA ho realizzato alcune parti di sviluppo (front-end e back-end) e bug fix relativi a progetti come Mercedes e Carrefour.</p>   <tag-lab>Java</tag-lab>  <tag-lab>Angular</tag-lab>  <tag-lab>Typescript</tag-lab>   ",
        trainee: "Jr Full Stack Web Developer Trainee",
        boolean: "Boolean Careers",
        period3: "<span class=\"clock\"><i class=\"fa fa-calendar\" aria-hidden=\"true\"></i></span> Feb 2021 - Lug 2021 </span>",
        mansion3: "<b>Trainee</b>",
        experience3Description: "Durante il corso Boolean ho realizzato progetti complessi che riproducono applicazioni web come WhatsApp Web, Netflix, Spotify, Digital Ocean e molti altri",
        education: "FORMAZIONE", 
        BooleanEducation: "Boolean",
        BooleanPlace1: "Full Remote specialization course",
        BooleanPeriodEducation: "<span class=\"clock\"><i class=\"fa fa-calendar\" aria-hidden=\"true\"></i></span> Feb 2021 - Jul 2021",
        BooleanDesc: "Corso intensivo di 6 mesi tenuto da sviluppatori senior. <tag-lab>HTML5</tag-lab> </tag-lab><tag-lab>Vue</tag-lab> <tag-lab>CSS3</tag-lab> <tag-lab>SCSS</tag-lab> <tag-lab>SASS</tag-lab> <tag-lab>SASS</tag-lab> <tag-lab>Flexbox</tag-lab> <tag-lab>Javascript</tag-lab> <tag-lab>Laravel</tag-lab> <tag-lab>php</tag-lab>",
        unicalEducation: "Laurea Triennale in Scienze della Comunicazione",
        placeUni: "Università della Calabria",
        periodEducation2: "<span class=\"clock\"><i class=\"fa fa-calendar\" aria-hidden=\"true\"></i></span> Set 2017 - Dec 2020",
        educationDesc2: "Tesi: Analisi sulla robustezza dei formati immagine",
        itis: "Diploma di informatica",
        itisPlace: "Istituto Tecnico Industriale E. Scalfaro - Catanzaro",
        itisPeriod: "<span class=\"clock\"><i class=\"fa fa-calendar\" aria-hidden=\"true\"></i></span> Set 2012 - Lug 2017",
        itisDesc: "Studio di vari linguaggi di programmazione come <tag-lab>C</tag-lab>  <tag-lab>C++</tag-lab>  <tag-lab>JAVA</tag-lab>  <tag-lab>SQL</tag-lab>  <tag-lab>Assembly</tag-lab>",
        contacts: "CONTATTAMI",
        emailTo: "Questo form inviera' una mail a ",
        robot: "Non sono un robot",
        msgSuccess: "Messaggio inviato con successo!",
        msgFail: "Impossibile inviare il messaggio. Contattami comunque tramite la mail: <a target='_blank' href='mailto:salvatore.butera1998@gmail.com'>salvatore.butera1998@gmail.com</a>",
        contactsFooter: "Contatti",
        links: "Link utili",
        gdpr: "Autorizzo il trattamento dei dati personali contenuti in questa pagina secondo l' art. 13 GDPR 679/16",
        downloadCv: " Puoi scaricare il mio cv <a target='_blank' href='/sbcvit.pdf' download>qui</a>",

        javascriptDesc:  "<strong>ESPERIENZA:</strong> 4 anni <div>Collegata a Boolean Careers e al periodo in NTT DATA</div>",
        bootstrapDesc: "<strong>ESPERIENZA:</strong> 4 anni <div>Collegata a Boolean Careers e al periodo in NTT DATA</div>",
        htmlDesc: "<strong>ESPERIENZA:</strong> 4 anni <div>Collegata a Boolean Careers e al periodo in NTT DATA</div>",
        cssDesc:  "<strong>ESPERIENZA:</strong> 4 anni <div>Collegata a Boolean Careers e al periodo in NTT DATA</div>",
        javaDesc:  "<strong>ESPERIENZA:</strong> 4 anni <div>Collegata a Boolean Careers e al periodo in NTT DATA</div>",
        angularDesc:  "<strong>ESPERIENZA:</strong> 4 anni <div>Collegata a Boolean Careers e al periodo in NTT DATA</div>",
        vueDesc:  "<strong>ESPERIENZA:</strong> 4 anni <div>Collegata a Boolean Careers e al periodo in NTT DATA</div>",
        typescriptDesc:  "<strong>ESPERIENZA:</strong> 4 anni <div>Collegata a Boolean Careers e al periodo in NTT DATA</div>",
        scssDesc:  "<strong>ESPERIENZA:</strong> 4 anni <div>Collegata a Boolean Careers e al periodo in NTT DATA</div>",
        blenderDesc:  "<strong>ESPERIENZA:</strong> 4 anni <div>Collegata a Boolean Careers e al periodo in NTT DATA</div>",
        threeDesc:  "<strong>ESPERIENZA:</strong> 4 anni <div>Collegata a Boolean Careers e al periodo in NTT DATA</div>",
        gitDesc:  "<strong>ESPERIENZA:</strong> 4 anni <div>Collegata a Boolean Careers e al periodo in NTT DATA</div>",
    },
    en: {
        name: "SALVATORE <br> BUTERA",
        description: "FRONT-END DEVELOPER",
        introductionTitle: "INTRODUCTION",
        introduction: "I am a Jr Full Stack Web Developer passionate about Computer Science and Graphic Design. I know how to use numerous frameworks for the development of web applications both on the front-end and the back-end side. I am always ready to challenge myself and learn new things every day.",
        experience: "EXPERIENCE",
        softwareDeveloper: "Software Developer Engineer",
        ntt: "NTT DATA",
        period1: "<span class=\"clock\"><i class=\"fa fa-clock-o\" aria-hidden=\"true\"></i></span> Feb 2022 - in progress </span> ",
        mansion1: "<b> Apprenticeship </b>",
        experienceDescription: "<tag-lab>Angular</tag-lab>  <tag-lab>Typescript</tag-lab>",
        fullStackDeveloper: "Junior Full Stack Developer",
        period2: "<span class=\"clock\"><i class=\"fa fa-calendar\" aria-hidden=\"true\"></i></span> Sep 2021 - Mar 2022 </span>",
        mansion2: "<b>Internship</b>",
        experience2Description: "During the internship at NTT DATA I made somedevelopment parts (front-end and back-end) and bug fixesrelated to projects such as Mercedes and Carrefour. <br>    <tag-lab>Java</tag-lab>  <tag-lab>Angular</tag-lab>  <tag-lab>Typescript</tag-lab>   ",
        trainee: "Jr Full Stack Web Developer Trainee",
        boolean: "Boolean Careers",
        period3: "<span class=\"clock\"><i class=\"fa fa-calendar\" aria-hidden=\"true\"></i></span> Feb 2021 - Jul 2021",
        mansion3: "<b>Trainee</b>",
        experience3Description: "During the Boolean course I made complex projects that reproduce web applications such as WhatsApp Web, Netflix, Spotify, Digital Ocean and many others",
        education: "EDUCATION",
        BooleanEducation: "Boolean",
        BooleanPlace1: "Full Remote specialization course",
        BooleanPeriodEducation: "<span class=\"clock\"><i class=\"fa fa-calendar\" aria-hidden=\"true\"></i></span> Feb 2021 - Jul 2021",
        BooleanDesc: "6-month full-time intensive course led by senior developers. <tag-lab>HTML5</tag-lab> </tag-lab><tag-lab>Vue</tag-lab> <tag-lab>CSS3</tag-lab> <tag-lab>SCSS</tag-lab> <tag-lab>SASS</tag-lab> <tag-lab>SASS</tag-lab> <tag-lab>Flexbox</tag-lab> <tag-lab>Javascript</tag-lab> <tag-lab>Laravel</tag-lab> <tag-lab>php</tag-lab>",
        unicalEducation: "University Degree in Scienze della Comunicazione",
        placeUni: "Università della Calabria",
        periodEducation2: "<span class=\"clock\"><i class=\"fa fa-calendar\" aria-hidden=\"true\"></i></span> Sep 2017 - Dec 2020",
        periodEducation2: "",
        educationDesc2: "Thesis: Analysis on robustness of image formats",
        itis: "High school diploma in Computer Science",
        itisPlace: "Istituto Tecnico Industriale E. Scalfaro - Catanzaro",
        itisPeriod: "<span class=\"clock\"><i class=\"fa fa-calendar\" aria-hidden=\"true\"></i></span> Sep 2012 - Jul 2017",
        itisDesc: "Basic and advanced knowledge of <tag-lab>C</tag-lab>  <tag-lab>C++</tag-lab>  <tag-lab>JAVA</tag-lab>  <tag-lab>SQL</tag-lab>  <tag-lab>Assembly</tag-lab>",
        contacts: "GET IN TOUCH",
        emailTo: "This form will send an e-mail to",
        robot: "I'm not a robot",
        msgSuccess: "Message sent!",
        msgFail: "Unable to send the message. Please contact me by email <a target='_blank' href='mailto:salvatore.butera1998@gmail.com'>salvatore.butera1998@gmail.com</a>",
        contactsFooter: "Contacts",
        links: "Links",
        gdpr: "I authorize the processing of personal data contained in my curriculum vitae based on art. 13 GDPR 679/16",
        downloadCv: "You can download my CV  <a target='_blank' href='/sbcvit.pdf' download>here</a>",

        javascriptDesc: "2 years experience <br> Connected to Boolean and NTT Data",
        bootstrapDesc: "2 years experience <br> Connected to Boolean and NTT Data",
        htmlDesc: "2 years experience <br> Connected to Boolean and NTT Data",
        cssDesc: "2 years experience <br> Connected to Boolean and NTT Data",
        javaDesc: "2 years experience <br> Connected to Boolean and NTT Data",
        angularDesc: "2 years experience <br> Connected to Boolean and NTT Data",
        typescriptDesc: "2 years experience <br> Connected to Boolean and NTT Data",
        scssDesc: "2 years experience <br> Connected to Boolean and NTT Data",
        blenderDesc: "2 years experience <br> self-taught ",
        threeDesc: "2 years experience <br> Connected to Boolean and NTT Data",
        gitDesc: "2 years experience <br> Connected to Boolean and NTT Data"
    },
    skillStart: {
        javascriptDesc: "01/01/2021",
        bootstrapDesc: "01/01/2021",
        htmlDesc: "01/01/2021",
        cssDesc: "01/01/2021",
        javaDesc: "01/01/2021",
        angularDesc: "01/01/2021",
        typescriptDesc: "01/01/2021",
        scssDesc: "01/01/2021",
        blenderDesc: "01/01/2021",
        threeDesc: "01/01/2021",
        gitDesc: "01/01/2021"
    }
}
        