export const translations = {
    it: {
        name: "SALVATORE <br> BUTERA",
        description: "JUNIOR FRONT-END DEVELOPER",
        introductionTitle: "INTRODUZIONE",
        introduction: "Sono un Jr Full Stack Web Developer appassionato di informatica e grafica. So utilizzare numerosi framework per lo sviluppo di applicazioni web sia lato front-end che back-end. Sono sempre pronto a sfidare me stesso e imparare cose nuove ogni giorno.",
        experience: "ESPERIENZA",
        softwareDeveloper: "Software Developer Engineer",
        ntt: "NTT DATA",
        period1: "<span class=\"date\"><span class=\"clock\"><i class=\"fa fa-clock-o\" aria-hidden=\"true\"></i></span> Feb 2022 - in corso </span> <b> Apprendistato </b>",
        experienceDescription: "<tag-lab>Angular</tag-lab>  <tag-lab>Typescript</tag-lab>",
        fullStackDeveloper: "Junior Full Stack Developer",
        period2: "<span class=\"date\"><span class=\"clock\"><i class=\"fa fa-calendar\" aria-hidden=\"true\"></i></span> Set 2021 - Mar 2022 </span> <b>Stage</b>",
        experience2Description: "<p>Durante lo stage presso NTT DATA ho realizzato alcune parti di sviluppo (front-end e back-end) e bug fix relativi a progetti come Mercedes e Carrefour.</p>   <tag-lab>Java</tag-lab>  <tag-lab>Angular</tag-lab>  <tag-lab>Typescript</tag-lab>   ",
        trainee: "Jr Full Stack Web Developer Trainee",
        boolean: "Boolean Careers",
        period3: "<span class=\"date\"><span class=\"clock\"><i class=\"fa fa-calendar\" aria-hidden=\"true\"></i></span> Feb 2021 - Lug 2021 </span> <b>Trainee</b>",
        experience3Description: "Durante il corso Boolean ho realizzato progetti complessi che riproducono applicazioni web come WhatsApp Web, Netflix, Spotify, Digital Ocean e molti altri",
        education: "FORMAZIONE", 
        BooleanEducation: "Boolean",
        BooleanPlace1: "Full Remote specialization course",
        BooleanPeriodEducation: "<span class=\"date\"><span class=\"clock\"><i class=\"fa fa-calendar\" aria-hidden=\"true\"></i></span> Feb 2021 - Jul 2021 </span>",
        BooleanDesc: "Corso intensivo di 6 mesi tenuto da sviluppatori senior. <tag-lab>HTML5</tag-lab> <tag-lab>CSS3</tag-lab> <tag-lab>SCSS</tag-lab> <tag-lab>SASS</tag-lab> <tag-lab>SASS</tag-lab> <tag-lab>Flexbox</tag-lab> <tag-lab>Javascript</tag-lab> <tag-lab>Laravel</tag-lab> <tag-lab>php</tag-lab>",
        unicalEducation: "Laurea Triennale in Scienze della Comunicazione",
        placeUni: "Università della Calabria",
        periodEducation2: "<span class=\"date\"><span class=\"clock\"><i class=\"fa fa-calendar\" aria-hidden=\"true\"></i></span> Set 2017 - Dec 2020 </span>",
        educationDesc2: "Tesi: Analisi sulla robustezza dei formati immagine",
        itis: "Diploma di informatica",
        itisPlace: "Istituto Tecnico Industriale E. Scalfaro - Catanzaro",
        itisPeriod: "<span class=\"date\"><span class=\"clock\"><i class=\"fa fa-calendar\" aria-hidden=\"true\"></i></span> Set 2012 - Lug 2017</span>",
        itisDesc: "Studio di vari linguaggi di programmazione come <tag-lab>C</tag-lab>  <tag-lab>C++</tag-lab>  <tag-lab>JAVA</tag-lab>  <tag-lab>SQL</tag-lab>  <tag-lab>Assembly</tag-lab>",
        contacts: "CONTATTAMI",
        emailTo: "Questo form inviera' una mail a ",
        robot: "Non sono un robot"
    },
    en: {
        name: "SALVATORE <br> BUTERA",
        description: "JUNIOR FRONT-END DEVELOPER",
        introductionTitle: "INTRODUCTION",
        introduction: "I am a Jr Full Stack Web Developer passionate about Computer Science and Graphic Design. I know how to use numerous frameworks for the development of web applications both on the front-end and the back-end side. I am always ready to challenge myself and learn new things every day.",
        experience: "EXPERIENCE",
        softwareDeveloper: "Software Developer Engineer",
        ntt: "NTT DATA",
        period1: "<span class=\"date\"><span class=\"clock\"><i class=\"fa fa-clock-o\" aria-hidden=\"true\"></i></span> Feb 2022 - in progress </span> <b> Apprenticeship </b>",
        experienceDescription: "<tag-lab>Angular</tag-lab>  <tag-lab>Typescript</tag-lab>",
        fullStackDeveloper: "Junior Full Stack Developer",
        period2: "<span class=\"date\"><span class=\"clock\"><i class=\"fa fa-calendar\" aria-hidden=\"true\"></i></span> Sep 2021 - Mar 2022 </span> <b>Internship</b>",
        experience2Description: "During the internship at NTT DATA I made somedevelopment parts (front-end and back-end) and bug fixesrelated to projects such as Mercedes and Carrefour. <br>    <tag-lab>Java</tag-lab>  <tag-lab>Angular</tag-lab>  <tag-lab>Typescript</tag-lab>   ",
        trainee: "Jr Full Stack Web Developer Trainee",
        boolean: "Boolean Careers",
        period3: "<span class=\"date\"><span class=\"clock\"><i class=\"fa fa-calendar\" aria-hidden=\"true\"></i></span> Feb 2021 - Jul 2021 </span> <b>Trainee</b>",
        experience3Description: "During the Boolean course I made complex projects that reproduce web applications such as WhatsApp Web, Netflix, Spotify, Digital Ocean and many others",
        education: "EDUCATION",
        BooleanEducation: "Boolean",
        BooleanPlace1: "Full Remote specialization course",
        BooleanPeriodEducation: "<span class=\"date\"><span class=\"clock\"><i class=\"fa fa-calendar\" aria-hidden=\"true\"></i></span> Feb 2021 - Jul 2021 </span>",
        BooleanDesc: "6-month full-time intensive course led by senior developers. <tag-lab>HTML5</tag-lab> <tag-lab>CSS3</tag-lab> <tag-lab>SCSS</tag-lab> <tag-lab>SASS</tag-lab> <tag-lab>SASS</tag-lab> <tag-lab>Flexbox</tag-lab> <tag-lab>Javascript</tag-lab> <tag-lab>Laravel</tag-lab> <tag-lab>php</tag-lab>",
        unicalEducation: "University Degree in Scienze della Comunicazione",
        placeUni: "Università della Calabria",
        periodEducation2: "<span class=\"date\"><span class=\"clock\"><i class=\"fa fa-calendar\" aria-hidden=\"true\"></i></span> Sep 2017 - Dec 2020 </span>",
        educationDesc2: "Thesis: Analysis on robustness of image formats",
        itis: "High school diploma in Computer Science",
        itisPlace: "Istituto Tecnico Industriale E. Scalfaro - Catanzaro",
        itisPeriod: "<span class=\"date\"><span class=\"clock\"><i class=\"fa fa-calendar\" aria-hidden=\"true\"></i></span> Sep 2012 - Jul 2017</span>",
        itisDesc: "Basic and advanced knowledge of <tag-lab>C</tag-lab>  <tag-lab>C++</tag-lab>  <tag-lab>JAVA</tag-lab>  <tag-lab>SQL</tag-lab>  <tag-lab>Assembly</tag-lab>",
        contacts: "GET IN TOUCH",
        emailTo: "This form will send an e-mail to",
        robot: "I'm not a robot"
    }
}
{/* <span class=\"clock\"><i class=\"fa fa-calendar\" aria-hidden=\"true\"></i></span> */}
