export const translations = {
    it: {
        name: "SALVATORE <br> BUTERA",
        description: "SVILUPPATORE FRONT-END",
        introductionTitle: "INTRODUZIONE",
        introduction: "Sono un Jr Full Stack Web Developer appassionato di informatica e grafica. So utilizzare numerosi framework per lo sviluppo di applicazioni web sia lato front-end che back-end. Sono sempre pronto a sfidare me stesso e imparare cose nuove ogni giorno.",
        experience: "ESPERIENZA",
        softwareDeveloper: "Software Developer Engineer",
        ntt: "NTT DATA",
        period1: "<span class=\"clock\"><i class=\"fa fa-clock-o\" aria-hidden=\"true\"></i></span> Feb 2022 - in corso </span>",
        mansion1: "<b> Apprendistato </b>",
        experienceDescription: "<tag-lab>Angular</tag-lab>  <tag-lab>Typescript</tag-lab>",
        fullStackDeveloper: "Junior Full Stack Developer",
        period2: "<span class=\"clock\"><i class=\"fa fa-calendar\" aria-hidden=\"true\"></i></span> Set 2021 - Mar 2022 </span> ",
        mansion2: "<b>Stage</b>",
        experience2Description: "<p>Durante lo stage presso NTT DATA ho realizzato alcune parti di sviluppo (front-end e back-end) e bug fix relativi a progetti come Mercedes e Carrefour.</p>   <tag-lab>Java</tag-lab>  <tag-lab>Angular</tag-lab>  <tag-lab>Typescript</tag-lab>   ",
        trainee: "Jr Full Stack Web Developer Trainee",
        boolean: "Boolean Careers",
        period3: "<span class=\"clock\"><i class=\"fa fa-calendar\" aria-hidden=\"true\"></i></span> Feb 2021 - Lug 2021 </span>",
        mansion3: "<b>Trainee</b>",
        experience3Description: "Durante il corso Boolean ho realizzato progetti complessi che riproducono applicazioni web come WhatsApp Web, Netflix, Spotify, Digital Ocean e molti altri",
        education: "FORMAZIONE", 
        BooleanEducation: "Boolean",
        BooleanPlace1: "Full Remote specialization course",
        BooleanPeriodEducation: "<span class=\"clock\"><i class=\"fa fa-calendar\" aria-hidden=\"true\"></i></span> Feb 2021 - Jul 2021",
        BooleanDesc: "Corso intensivo di 6 mesi tenuto da sviluppatori senior. <tag-lab>HTML5</tag-lab> <tag-lab>CSS3</tag-lab> <tag-lab>SCSS</tag-lab> <tag-lab>SASS</tag-lab> <tag-lab>SASS</tag-lab> <tag-lab>Flexbox</tag-lab> <tag-lab>Javascript</tag-lab> <tag-lab>Laravel</tag-lab> <tag-lab>php</tag-lab>",
        unicalEducation: "Laurea Triennale in Scienze della Comunicazione",
        placeUni: "Università della Calabria",
        periodEducation2: "<span class=\"clock\"><i class=\"fa fa-calendar\" aria-hidden=\"true\"></i></span> Set 2017 - Dec 2020",
        educationDesc2: "Tesi: Analisi sulla robustezza dei formati immagine",
        itis: "Diploma di informatica",
        itisPlace: "Istituto Tecnico Industriale E. Scalfaro - Catanzaro",
        itisPeriod: "<span class=\"clock\"><i class=\"fa fa-calendar\" aria-hidden=\"true\"></i></span> Set 2012 - Lug 2017",
        itisDesc: "Studio di vari linguaggi di programmazione come <tag-lab>C</tag-lab>  <tag-lab>C++</tag-lab>  <tag-lab>JAVA</tag-lab>  <tag-lab>SQL</tag-lab>  <tag-lab>Assembly</tag-lab>",
        contacts: "CONTATTAMI",
        emailTo: "Questo form inviera' una mail a ",
        robot: "Non sono un robot",
        msgSuccess: "Messaggio inviato con successo!",
        msgFail: "Impossibile inviare il messaggio. Contattami comunque tramite la mail: <a target='_blank' href='mailto:salvatore.butera1998@gmail.com'>salvatore.butera1998@gmail.com</a>",
        contactsFooter: "Contatti",
        links: "Link utili",
        gdpr: "Autorizzo il trattamento dei dati personali contenuti in questa pagina secondo l' art. 13 GDPR 679/16",
        downloadCv: " Puoi scaricare il mio cv <a target='_blank' href='/sbcvit.pdf' download>qui</a>",

        javascriptDesc: "Ho ampiamente utilizzato javascript durante il Boolean Trainee e durante la fase di sviluppo dei miei progetti personali. Ho sviluppato buone conoscenze su questo meraviglioso linguaggio di programmazione",
        bootstrapDesc: "Bootstrap è un grande miglioramento in termini di manutenibilità del codice e tempo di sviluppo. Ho utilizzato questo framework CSS in diversi progetti in NTT e durante il Boolean Trainee",
        htmlDesc: "Ho imparato a padroneggiare l'HTML durante questi anni come sviluppatore front-end",
        cssDesc: "Adoro personalizzare e stilizzare siti web con la magia del CSS",
        javaDesc: "Java è il linguaggio di programmazione grazie al quale ho imparato l'OOP. Durante il mio periodo in NTT DATA ho sviluppato dei microservizi SOAP con JAVA per un software che gestisce i magazzini Carrefour.",
        angularDesc: " Ho sviluppato buone conoscenze angular lavorando in NTT DATA su progetti che utilizzano questa tecnologia ",
        typescriptDesc: "Ho implementato e programmato in Typescript per i progetti Angular di NTT DATA",
        scssDesc: "Mi sono avvicinato a questo prepocessore durante Boolean. Conoscenza che poi ho riapplicato per quasi tutti i progetti front-end su cui ho lavorato in NTT.",
        blenderDesc: "Sono sempre stato appassionato di CGI e grafica 3D e ho ottenuto un buon livello di abilità come autodidatta grazie a molta pratica, tutorial e documentazione in parallelo con i miei studi di Comunicazione",
        threeDesc: "Three js è un meraviglioso framework che uso per integrare elementi 3D nei siti Web.",
        gitDesc: " "
    },
    en: {
        name: "SALVATORE <br> BUTERA",
        description: "FRONT-END DEVELOPER",
        introductionTitle: "INTRODUCTION",
        introduction: "I am a Jr Full Stack Web Developer passionate about Computer Science and Graphic Design. I know how to use numerous frameworks for the development of web applications both on the front-end and the back-end side. I am always ready to challenge myself and learn new things every day.",
        experience: "EXPERIENCE",
        softwareDeveloper: "Software Developer Engineer",
        ntt: "NTT DATA",
        period1: "<span class=\"clock\"><i class=\"fa fa-clock-o\" aria-hidden=\"true\"></i></span> Feb 2022 - in progress </span> ",
        mansion1: "<b> Apprenticeship </b>",
        experienceDescription: "<tag-lab>Angular</tag-lab>  <tag-lab>Typescript</tag-lab>",
        fullStackDeveloper: "Junior Full Stack Developer",
        period2: "<span class=\"clock\"><i class=\"fa fa-calendar\" aria-hidden=\"true\"></i></span> Sep 2021 - Mar 2022 </span>",
        mansion2: "<b>Internship</b>",
        experience2Description: "During the internship at NTT DATA I made somedevelopment parts (front-end and back-end) and bug fixesrelated to projects such as Mercedes and Carrefour. <br>    <tag-lab>Java</tag-lab>  <tag-lab>Angular</tag-lab>  <tag-lab>Typescript</tag-lab>   ",
        trainee: "Jr Full Stack Web Developer Trainee",
        boolean: "Boolean Careers",
        period3: "<span class=\"clock\"><i class=\"fa fa-calendar\" aria-hidden=\"true\"></i></span> Feb 2021 - Jul 2021",
        mansion3: "<b>Trainee</b>",
        experience3Description: "During the Boolean course I made complex projects that reproduce web applications such as WhatsApp Web, Netflix, Spotify, Digital Ocean and many others",
        education: "EDUCATION",
        BooleanEducation: "Boolean",
        BooleanPlace1: "Full Remote specialization course",
        BooleanPeriodEducation: "<span class=\"clock\"><i class=\"fa fa-calendar\" aria-hidden=\"true\"></i></span> Feb 2021 - Jul 2021",
        BooleanDesc: "6-month full-time intensive course led by senior developers. <tag-lab>HTML5</tag-lab> <tag-lab>CSS3</tag-lab> <tag-lab>SCSS</tag-lab> <tag-lab>SASS</tag-lab> <tag-lab>SASS</tag-lab> <tag-lab>Flexbox</tag-lab> <tag-lab>Javascript</tag-lab> <tag-lab>Laravel</tag-lab> <tag-lab>php</tag-lab>",
        unicalEducation: "University Degree in Scienze della Comunicazione",
        placeUni: "Università della Calabria",
        periodEducation2: "<span class=\"clock\"><i class=\"fa fa-calendar\" aria-hidden=\"true\"></i></span> Sep 2017 - Dec 2020",
        periodEducation2: "",
        educationDesc2: "Thesis: Analysis on robustness of image formats",
        itis: "High school diploma in Computer Science",
        itisPlace: "Istituto Tecnico Industriale E. Scalfaro - Catanzaro",
        itisPeriod: "<span class=\"clock\"><i class=\"fa fa-calendar\" aria-hidden=\"true\"></i></span> Sep 2012 - Jul 2017",
        itisDesc: "Basic and advanced knowledge of <tag-lab>C</tag-lab>  <tag-lab>C++</tag-lab>  <tag-lab>JAVA</tag-lab>  <tag-lab>SQL</tag-lab>  <tag-lab>Assembly</tag-lab>",
        contacts: "GET IN TOUCH",
        emailTo: "This form will send an e-mail to",
        robot: "I'm not a robot",
        msgSuccess: "Message sent!",
        msgFail: "Unable to send the message. Please contact me by email <a target='_blank' href='mailto:salvatore.butera1998@gmail.com'>salvatore.butera1998@gmail.com</a>",
        contactsFooter: "Contacts",
        links: "Links",
        gdpr: "I authorize the processing of personal data contained in my curriculum vitae based on art. 13 GDPR 679/16",
        downloadCv: "You can download my CV  <a target='_blank' href='/sbcvit.pdf' download>here</a>",

        javascriptDesc: "I largely used javascript during the Boolean Trainee and during the developing phase of my personal projects. I developed intermediate knowledge about this wonderful programming language",
        bootstrapDesc: "Bootstrap is a great improvement in terms of code manutenibility and development time. I used this CSS framework in several project in NTT and during the Boolean Trainee",
        htmlDesc: "I can build semantic HTML code thanks to my experience. I mastered this skill during these years as front-end developer",
        cssDesc: "What kind of front-end developer would I be if i did not know CSS? I love customize and stylize websites and projects with good CSS lines",
        javaDesc: "Java is the programming language thanks to wich i learned OOP. During my period in NTT DATA I developed various SOAP micro-services with JAVA for a software that manage Carrefour warehouses.",
        angularDesc: " I developed this skill working in NTT DATA on numerous projects",
        typescriptDesc: "This skill is closely related to angular and it hasn't been a problem for me switching from javascript to typescript",
        scssDesc: "I approached this prepocessor during Boolean and I think that is a powerful tool. The NTT projects that I worked on make use of it.",
        blenderDesc: "I have been always passionate about CGI and 3D graphics and I obtained a good skilled level as a self-thought thanks to a lot of practice, tutorials and documentation in parallel with my Communication studies",
        threeDesc: "Recently I entered this wonderful world that I am still learning during weekends and holidays",
        gitDesc: "I use GIT every day to record the changes made to a project, storing those changes, then allowing my teams to reference them as needed.",
    }
}
{/* <span class=\"clock\"><i class=\"fa fa-calendar\" aria-hidden=\"true\"></i></span> */}
        